spring.application.name=crud-academia

server.port=${API_PORT:8080}

spring.datasource.url=${DB_URI:jdbc:postgresql://localhost:5432/crud_academia}
spring.datasource.username=${DB_USER:academia_user}
spring.datasource.password=${DB_PASSWORD:academia_pass}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:3000}
